- name: SES7-admins-ceph-salt-config
  hosts: admins
  become: true
  tasks:
    - name: configuring salt
      shell: |
        ceph-salt config /ceph_cluster/minions add '*'
        ceph-salt config /ceph_cluster/roles/cephadm add '*'
        ceph-salt config /ceph_cluster/roles/admin add admin.ses7
        ceph-salt config /ceph_cluster/roles/bootstrap set osd-1.ses7
        ceph-salt config /cephadm_bootstrap/mon_ip set 10.96.201.102
        ceph-salt config /ssh generate
        ceph-salt config /time_server/servers add admin.ses7
        ceph-salt config /time_server/external_servers add pool.ntp.org
        ceph-salt config /time_server/subnet set 10.96.201.0/24
        ceph-salt config /cephadm_bootstrap/dashboard/username set admin
        ceph-salt config /cephadm_bootstrap/dashboard/password set admin
        ceph-salt config /cephadm_bootstrap/dashboard/force_password_update disable
        ceph-salt config /cephadm_bootstrap/ceph_image_path set registry.suse.de/devel/storage/7.0/containers/ses/7/ceph/ceph
        ceph-salt config /cephadm_bootstrap/ceph_conf add global
        ceph-salt config /cephadm_bootstrap/ceph_conf/global set cluster_network 10.95.201.0/24
      register: shell_output
    - debug:
        var: shell_output.stdout_lines